### ISSUE TITLE
Remove milliseconds from SerialWithTime 

### ISSUE THREAD

**Issue by prestoncarman** [Open-Acidification/TankController#146]
It does not make sense to append uptime milliseconds to RTC datetime. We need to display milliseconds in a different way. Lets discuss alternate options:

* Show device uptime
* Show delta since last called
* ...

**Comment by jgfoster** [comment]
After some discussions with Eliam, it occurs to me that the reason I added the milliseconds was so you could do the mental arithmetic of calculating how long it had been since the solenoid had changed. Instead let's just tell the user how long it has been! So we just say "heater off after 400 ms". 

With this I'd like to retire `serialWithTime()` and change Serial_TC::vprintf() so that it keeps track of the last serial event time and if it has been more that a minute (for example) it adds a timestamp.

**Comment by jgfoster** [comment]
Fixed #150.

**Comment by jgfoster** [comment]
Done!
